In [1]:
# Emily Lewis
# OCNG 689
# Homework 3
import numpy as np

In [2]:
#1 Vector manipulation
a = np.zeros(10)
a[4]=1
a

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [3]:
#2 Vector range
b = np.arange(10,50,1)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#3 Reverse a vector
def reverse(x):
    '''return a 1D vector with the elements reversed
        Input
    -----
        x: 1D array
    Output
    ------
        res: 1D array, with the elements of `x` reversed '''
    return x[::-1]

x=np.array([1,2,3,4,5,6,7,8])
reverse(x)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [5]:
#4 Find indices of non-zero elements
# one way to do 4
def find_nonzero(z):
    return np.nonzero(z)
x=np.array([1,2,0,0,4,0])
w = find_nonzero(x)

print(w)
y = x[find_nonzero(x)]
print(y)
# type(y)

(array([0, 1, 4]),)
[1 2 4]


In [6]:
# better way to do 4
def find_nonzero(z):
    '''return the indices of non-zero elements of an array.
        Input:      x:  array
        Output:     indices: array of integer indices'''
    nonzero=[]
    for i,w in enumerate(z):
        if w !=0:
            nonzero.append(i)
        else: continue
    return nonzero

x=np.array([1,2,0,0,4,0])
print('These are the indices:', find_nonzero(x))
z=x[find_nonzero(x)]
print('Used function to get nonzero values:', z)

These are the indices: [0, 1, 4]
Used function to get nonzero values: [1 2 4]


In [7]:
# explaination of enumerate
words = ['cats','radar','stars']
for i,word in enumerate(words):
    print(i)
    print(word)
    

0
cats
1
radar
2
stars


In [8]:
#5 Array with random values
#np.random.normal(loc=0,scale=1,size=None)
# loc is mean... mu of distribution >> 0 for this problem
# scale is standard deviation >> 1 in this case
z = np.random.normal(0,1,(3,3,3))
print(z)

[[[ 0.02634368  0.08671024 -0.88204354]
  [-1.1598874   0.89299364  1.62187607]
  [-0.60044434 -0.15556792 -0.45329234]]

 [[-1.86368311 -0.71023478  0.88363552]
  [-0.00868098 -1.13652343  0.70430637]
  [-0.33180009 -0.41984449 -0.12350629]]

 [[-1.11990261  1.44682591 -0.61405417]
  [ 0.49558939  1.64382213  0.915758  ]
  [-0.1025332   0.22084156  0.29943824]]]


In [9]:
#6 Operations on an array with random values
x=np.random.rand(10,10)
print(x)

# min 2nd row
#axis 1 is for rows ... axis 0 is for columns
# [1] makes it the second row specifically
y=x.min(axis=1)[1]
print('Minimm of 2nd row: ',y)

# max 4th column
# this returns maximum values for all the columns
# [3] makes it the fourth column specifically 
z=x.max(axis=0)[3]
print('Maximum of 4th column:',z)

[[ 0.41144331  0.3681097   0.67297216  0.09568757  0.15950511  0.60782714
   0.39237251  0.3003297   0.39770748  0.46851694]
 [ 0.78462111  0.30703774  0.40719018  0.23020348  0.34430374  0.8727767
   0.33606555  0.50575233  0.24148091  0.77954518]
 [ 0.20855689  0.40095124  0.82122234  0.77451733  0.08820686  0.33337463
   0.12335645  0.38988377  0.65355074  0.88424287]
 [ 0.45128268  0.86047429  0.51168041  0.37316527  0.33869875  0.10057183
   0.09733393  0.47390451  0.62860614  0.97988959]
 [ 0.42771034  0.80764384  0.89011113  0.05659971  0.53316375  0.32734118
   0.45065232  0.32162177  0.33865422  0.89053532]
 [ 0.34271867  0.68822646  0.55717202  0.56874368  0.92528673  0.31163103
   0.64322066  0.81094155  0.0235478   0.88208726]
 [ 0.0845931   0.55447795  0.29828049  0.68833258  0.51134308  0.57514555
   0.42344177  0.48785102  0.87845094  0.15227325]
 [ 0.76863452  0.96961274  0.51714782  0.75395247  0.12098669  0.54451435
   0.08885375  0.28377418  0.44123433  0.21808134]
 

In [10]:
#7 Vector without end points
x = np.linspace(0,1,12)[1:11]
print(x)
x.size

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


10

In [11]:
#8 Sorted random vector
e = np.random.rand(10)
print(e)
e.sort()
e

[ 0.69773744  0.28297675  0.01216718  0.50799161  0.38091549  0.88668476
  0.24124097  0.95520835  0.75570013  0.16312233]


array([ 0.01216718,  0.16312233,  0.24124097,  0.28297675,  0.38091549,
        0.50799161,  0.69773744,  0.75570013,  0.88668476,  0.95520835])

In [12]:
#9 Test for array equality
def is_equal(A,B):
    '''Inputs:
            A, B:  array
        Output:
            Bool:  True if A and B have the same shape and identical elements.'''
    return A == B

C=(np.array[1,2,3,4])
D=(np.array[1,2,3,4,5])
print(is_equal(C,D))

E=(np.array[4,3,2])
F=(np.array[4,3,2])
print(is_equal(E,F))

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
#10 Subtract the row mean from rows of a matrix
g=np.random.rand(3,3)
print('Original matrix:\n ',g)
y=g.mean(axis=1)
print('mean of the rows: ', y)

def sub_row_mean(x):
    '''Takes matrix and subtracts row mean from rows'''
    y=x.mean(axis=1, keepdims=True)
    z = x - y
    return z

sub_row_mean(g)

In [ ]:
#11 Multiply arrays
a=np.random.rand(5,5,3)
b=np.random.rand(5,5)
sol1 = a*b[:,:,None] # this is to fix the size so they can be multiplied 
print(sol1)

c=np.random.rand(3,5,5)
d=np.random.rand(5,5)
sol2 = c*d
print(sol2)

In [ ]:
#12 Creating a new array
Z=np.arange(1,15,1)
print('This is Z:\n',Z)
# R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

# k=array([])
#type(k)
k = []
for n in Z:
    if n < 12:
        n = np.array([n,n+1,n+2,n+3])
        k.append(n)
        R=np.asarray(k)        # this makes R return as an array 
    elif n == 12 or n == 13:   # this keeps the array from printing three times
        continue
    else:                      # the array only prints once for the value n = 14
        print('This is R:\n',R)

In [ ]:
#13 Convert from Cartesian to polar coordinates
def cart2polar(xy):
    '''Return equivalent polar coordinates of specified cartesian points.
    Inputs:
        xy: array
             Nx2 array of Cartesian coordinates, with columns x and y respectively.
    Returns:
        rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively'''   
    x = xy[:,0]
    y = xy[:,1]
    r = np.sqrt(x**2 + y**2)
    p = np.arctan2(y, x)
    return(np.transpose(np.array([r,p])))

# a=np.random.rand(2,2)
# print(a)
b = np.array([[1,2],[3,5],[2,7]])
cart2polar(b)

In [ ]:
#14 Compute and time for loops and array operations.
import time

a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers

time3 = time.time()
# print(time3)

sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.


time1 = time.time()
print('This is time1: ', time1)

# (n, k, j, i) 

sol2 = np.empty_like(sol)
for n in range(a.shape[0]):
    for k in range(a.shape[1]):
        for j in range(a.shape[2]):
            for i in range(a.shape[3]):
                sol2[n, k, j, i] = a[n, k, j, i] * b[n, k, j, i]    

time2 = time.time()
# print('This is time2: ', time2)

# print(time2-time1)

ratio=((time2-time1)/(time1-time3))
print('ratio of sol2/sol: ', ratio)

# type(np.shape(a))
# a.shape
# list(range(3))

In [ ]:
np.all(sol==sol2)

In [ ]:
#15 Fix the code
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]/4 # I added /4 to change value of aa (which is part of a)
#     aa /= 4.        # having /4 in this line did not change value of aa so it ramained a 2x2 of zeroes 
    a[:2, :] -= aa
    bb = b[:,None] # I added this row to make the array able to multiply by each other (fixed shape issue)
#     print(aa)
#     print(bb)
#     print('end')
    return a*bb # changed this to the new bb instead of just b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)
# print(a)
# print('this')
# print(a[:2, :])
# print(b)
print(res)
assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

In [ ]:
#16 Calculate components of a vector

data = np.loadtxt('burl1h2010.txt')
# WDIR wind direction
vdir_data = data[:,5]
# WSPD wind speed
vspd_data = data[:,6]
    
def component_vector(vdir,vspd):
    '''Take in vector and return components.
        Inputs:
            vdir: vector direction in degrees
            vspd: vector magnitude
        Returns:
            u: x component of vector
            v: y component of vector'''
    
    vdird = np.radians(vdir)
    u = vspd*np.cos(vdird)
    v = vspd*np.sin(vdird)
    return ([u],[v])

# component_vector(150,6)
component_vector(vdir_data, vspd_data)

In [ ]:
#17 (Grad) Write and use a class

# be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values
#     found in the file;
# contain a method, salt_mean, which returns the mean of the salinity;
# contain a method, temp_max, which returns the maximum value of the temperature values.

# loop for general case then with the glob

class dataclass(object):
    
        def __init__(self, filename):
            switch = 0
            self.temp = []
            self.sal = []
            self.f= filename
            f = open(filename)
            
            for line in f.readlines():
                if switch == 1:
                    self.temp.append(line.split()[2])
                    self.sal.append(line.split()[5])
                if line.split()[0] == '*END*': switch = 1
                    
            self.temp = np.asarray(self.temp, dtype = 'float64')
            self.sal = np.asarray(self.sal, dtype = 'float64')
        
        def salt_mean(self):
            saltmean = np.mean(sal)
            return ('This is the mean of the salinity:', saltmean)
    
        def temp_max(self):
            tempmax = np.max(temp)
            return ('This is the maximum temperature value:', tempmax)      
        
        
import glob
filegroup = glob.glob('../python4geosciences/data/MCH/*.cnv2')
# mch('../python4geosciences/data/MCH/m1001a.cnv2')
wind = []
for filename in filegroup:
#     print(filename)
    wind.append(dataclass(filename))
print(wind[1].f)
print(wind[1].sal)
print(wind[1].temp)

In [ ]:
is_equal?

In [18]:
#18 (Grad) Running mean

def vect_running_mean(vect,N):
    '''Return the running average of a vector, with averaging window of size N.

    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    Outputs:
        out: Vector of running-averaged values; same size as vec'''

    y = np.zeros((len(vect),))
#     if N == 0:
#         return vect
#     else:
    for z in range(len(vect)):
#         fixing for end ranges
#         if z < N
        while z > N:
            y[x] = np.sum(vect[z:(z+N+1)]) + np.sum(vect[(z-N):z])
            #sums = 
        else:
            y[z] = np.sum(vect[z:(z+N+1)]) + np.sum(vect[(z-N):z])
    return y/(2*N+1)

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,1,1,1,1,1,1])
#vect_running_mean(b,0)
vect_running_mean(b,1)

IndexError: arrays used as indices must be of integer (or boolean) type

In [21]:

#18 (Grad) Running mean

def vect_running_mean(vect,N):
    '''Return the running average of a vector, with averaging window of size N.

    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    Outputs:
        out: Vector of running-averaged values; same size as vec'''

    y = np.zeros((len(vect),))
#     if N == 0:
#         return vect
#     else:
    for z in range(len(vect)):
#         fixing for end ranges
#         if z == 
        y[z] = np.sum(vect[z:(z+N+1)]) + np.sum(vect[(z-N):z])
    return y/(2*N+1)

vect_running_mean(b,2)

array([ 0.6,  0.6,  1. ,  1. ,  1. ,  0.8,  0.6])