In [1]:
# Emily Lewis
# OCNG 689
# Homework 3
import numpy as np

In [2]:
#1 Vector manipulation
a = np.zeros(10)
a[4]=1
a

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [3]:
#2 Vector range
b = np.arange(10,50,1)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#3 Reverse a vector
def reverse(x):
    '''return a 1D vector with the elements reversed
        Input
    -----
        x: 1D array
    Output
    ------
        res: 1D array, with the elements of `x` reversed '''
    return x[::-1]

x=np.array([1,2,3,4,5,6,7,8])
reverse(x)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [5]:
#4 Find indices of non-zero elements
# one way to do 4
def find_nonzero(z):
    return np.nonzero(z)
x=np.array([1,2,0,0,4,0])
w = find_nonzero(x)

print(w)
y = x[find_nonzero(x)]
print(y)
# type(y)

(array([0, 1, 4]),)
[1 2 4]


In [6]:
# better way to do 4
def find_nonzero(z):
    '''return the indices of non-zero elements of an array.
        Input:      x:  array
        Output:     indices: array of integer indices'''
    nonzero=[]
    for i,w in enumerate(z):
        if w !=0:
            nonzero.append(i)
        else: continue
    return nonzero

x=np.array([1,2,0,0,4,0])
print('These are the indices:', find_nonzero(x))
z=x[find_nonzero(x)]
print('Used function to get nonzero values:', z)

These are the indices: [0, 1, 4]
Used function to get nonzero values: [1 2 4]


In [7]:
# explaination of enumerate
words = ['cats','radar','stars']
for i,word in enumerate(words):
    print(i)
    print(word)
    

0
cats
1
radar
2
stars


In [8]:
#5 Array with random values
#np.random.normal(loc=0,scale=1,size=None)
# loc is mean... mu of distribution >> 0 for this problem
# scale is standard deviation >> 1 in this case
z = np.random.normal(0,1,(3,3,3))
print(z)

[[[ 0.33617343  0.60310034 -0.08548648]
  [-0.68857185  0.77464178 -3.26163698]
  [-0.39818923  0.41835169 -0.2132755 ]]

 [[ 0.64132308 -2.2190436  -0.82726127]
  [ 0.1346616   0.29387739  1.77480668]
  [-0.68035831 -0.3632023  -0.06460752]]

 [[-2.08826263 -0.29943552  0.82063522]
  [ 0.24257444 -0.80629231 -0.60334654]
  [-0.01816199 -0.55554285  0.48140283]]]


In [9]:
#6 Operations on an array with random values
x=np.random.rand(10,10)
print(x)

# min 2nd row
#axis 1 is for rows ... axis 0 is for columns
# [1] makes it the second row specifically
y=x.min(axis=1)[1]
print('Minimm of 2nd row: ',y)

# max 4th column
# this returns maximum values for all the columns
# [3] makes it the fourth column specifically 
z=x.max(axis=0)[3]
print('Maximum of 4th column:',z)

[[ 0.5361064   0.49917859  0.96440112  0.58772519  0.46627244  0.86519677
   0.31051372  0.62385802  0.7363215   0.87604199]
 [ 0.04092334  0.62570896  0.71064976  0.72865532  0.5654592   0.47083671
   0.71653877  0.74755334  0.93887648  0.06970503]
 [ 0.98416958  0.97308323  0.54763774  0.08585048  0.59098138  0.87025358
   0.76894493  0.76335486  0.03270963  0.45106847]
 [ 0.02664655  0.71501266  0.43891138  0.48736516  0.13353763  0.2307266
   0.38253477  0.88792565  0.88890647  0.47815269]
 [ 0.83975891  0.83721476  0.486111    0.00969109  0.95906894  0.96362055
   0.85697733  0.62213012  0.82635913  0.36914027]
 [ 0.01060639  0.15142999  0.4513595   0.48022061  0.28259587  0.60414444
   0.43139262  0.03769808  0.31355324  0.88837513]
 [ 0.97941426  0.87785032  0.37795281  0.81427002  0.02055959  0.85232424
   0.64978958  0.47846351  0.34790141  0.0817499 ]
 [ 0.61572586  0.22299423  0.80513515  0.63988033  0.65373753  0.80529892
   0.94623524  0.11998     0.13829584  0.61281493]
 

In [10]:
#7 Vector without end points
x = np.linspace(0,1,12)[1:11]
print(x)
x.size

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


10

In [11]:
#8 Sorted random vector
e = np.random.rand(10)
print(e)
e.sort()
e

[ 0.30142177  0.4035029   0.58445804  0.72293555  0.34912614  0.32570081
  0.02071056  0.6831961   0.64343562  0.54907142]


array([ 0.02071056,  0.30142177,  0.32570081,  0.34912614,  0.4035029 ,
        0.54907142,  0.58445804,  0.64343562,  0.6831961 ,  0.72293555])

In [94]:
#9 Test for array equality
def is_equal(A,B):
    '''Inputs:
            A, B:  array
        Output:
            Bool:  True if A and B have the same shape and identical elements.'''
    return A == B

C=(1,2,3,4)
D=(1,2,3,4,5)
print(is_equal(C,D))

E=(4,3,2)
F=(4,3,2)
print(is_equal(E,F))

False
True


In [13]:
#10 Subtract the row mean from rows of a matrix
g=np.random.rand(3,3)
print('Original matrix:\n ',g)
y=g.mean(axis=1)
print('mean of the rows: ', y)

def sub_row_mean(x):
    '''Takes matrix and subtracts row mean from rows'''
    y=x.mean(axis=1, keepdims=True)
    z = x - y
    return z

sub_row_mean(g)

Original matrix:
  [[ 0.94423542  0.98592651  0.06659427]
 [ 0.64266249  0.36156987  0.50405238]
 [ 0.60992601  0.42657291  0.64455511]]
mean of the rows:  [ 0.6655854   0.50276158  0.56035134]


array([[ 0.27865002,  0.32034111, -0.59899113],
       [ 0.13990091, -0.14119171,  0.0012908 ],
       [ 0.04957467, -0.13377843,  0.08420377]])

In [14]:
#11 Multiply arrays
a=np.random.rand(5,5,3)
b=np.random.rand(5,5)
sol1 = a*b[:,:,None] # this is to fix the size so they can be multiplied 
print(sol1)

c=np.random.rand(3,5,5)
d=np.random.rand(5,5)
sol2 = c*d
print(sol2)

[[[ 0.2238587   0.13543386  0.38552137]
  [ 0.30602993  0.34519163  0.28679396]
  [ 0.41024907  0.21766159  0.30128536]
  [ 0.11266892  0.11569691  0.09543314]
  [ 0.08633824  0.26604232  0.17107487]]

 [[ 0.11260307  0.00561819  0.17774707]
  [ 0.06932634  0.30855532  0.2812141 ]
  [ 0.44055771  0.16869393  0.19931745]
  [ 0.26501819  0.60007966  0.49811752]
  [ 0.23140484  0.0711991   0.17099414]]

 [[ 0.20850677  0.7740102   0.30782317]
  [ 0.30500902  0.01244784  0.12107466]
  [ 0.04026814  0.11865015  0.09770069]
  [ 0.12582734  0.20918215  0.3186882 ]
  [ 0.00376728  0.02069461  0.02578011]]

 [[ 0.70528038  0.69670656  0.43119238]
  [ 0.60976069  0.13198957  0.67222604]
  [ 0.16295584  0.00818786  0.44726261]
  [ 0.07393047  0.14814553  0.22188221]
  [ 0.05620297  0.62680339  0.61607816]]

 [[ 0.21742616  0.45772415  0.51222704]
  [ 0.15854142  0.23649065  0.02896448]
  [ 0.02065294  0.09019391  0.12180698]
  [ 0.11967125  0.08315829  0.0233738 ]
  [ 0.05238348  0.12175436  0.08

In [102]:
#12 Creating a new array
Z=np.arange(1,15,1)
print('This is Z:\n',Z)
# R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

# k=array([])
#type(k)
k = []
for n in Z:
    if n < 12:
        n = np.array([n,n+1,n+2,n+3])
        k.append(n)
        R=np.asarray(k)        # this makes R return as an array 
    elif n == 12 or n == 13:   # this keeps the array from printing three times
        continue
    else:                      # the array only prints once for the value n = 14
        print('This is R:\n',R)

This is Z:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
This is R:
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [16]:
#13 Convert from Cartesian to polar coordinates
def cart2polar(xy):
    '''Return equivalent polar coordinates of specified cartesian points.
    Inputs:
        xy: array
             Nx2 array of Cartesian coordinates, with columns x and y respectively.
    Returns:
        rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively'''   
    x = xy[:,0]
    y = xy[:,1]
    r = np.sqrt(x**2 + y**2)
    p = np.arctan2(y, x)
    return(np.transpose(np.array([r,p])))

# a=np.random.rand(2,2)
# print(a)
b = np.array([[1,2],[3,5],[2,7]])
cart2polar(b)

array([[ 2.23606798,  1.10714872],
       [ 5.83095189,  1.03037683],
       [ 7.28010989,  1.29249667]])

In [106]:
#14 Compute and time for loops and array operations.
import time

a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers

time3 = time.time()
# print(time3)

sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.


time1 = time.time()
# print('This is time1: ', time1)

# (n, k, j, i) 

sol2 = np.empty_like(sol)
for n in range(a.shape[0]):
    for k in range(a.shape[1]):
        for j in range(a.shape[2]):
            for i in range(a.shape[3]):
                sol2[n, k, j, i] = a[n, k, j, i] * b[n, k, j, i]    

time2 = time.time()
# print('This is time2: ', time2)

# print(time2-time1)

ratio=((time2-time1)/(time1-time3))
print('ratio of sol2/sol: ', ratio)

# type(np.shape(a))
# a.shape
# list(range(3))

ratio of sol2/sol 15.719438877755511


In [96]:
np.all(sol==sol2)

True

In [18]:
#15 Fix the code
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]/4 # I added /4 to change value of aa (which is part of a)
#     aa /= 4.        # having /4 in this line did not change value of aa so it ramained a 2x2 of zeroes 
    a[:2, :] -= aa
    bb = b[:,None] # I added this row to make the array able to multiply by each other (fixed shape issue)
#     print(aa)
#     print(bb)
#     print('end')
    return a*bb # changed this to the new bb instead of just b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)
# print(a)
# print('this')
# print(a[:2, :])
# print(b)
print(res)
assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

[[ 2.25  2.25]
 [ 2.25  2.25]
 [ 3.    3.  ]]


In [19]:
#16 Calculate components of a vector

data = np.loadtxt('burl1h2010.txt')
# WDIR wind direction
vdir_data = data[:,5]
# WSPD wind speed
vspd_data = data[:,6]
    
def component_vector(vdir,vspd):
    '''Take in vector and return components.
        Inputs:
            vdir: vector direction in degrees
            vspd: vector magnitude
        Returns:
            u: x component of vector
            v: y component of vector'''
    
    vdird = np.radians(vdir)
    u = vspd*np.cos(vdird)
    v = vspd*np.sin(vdird)
    return ([u],[v])

# component_vector(150,6)
component_vector(vdir_data, vspd_data)

([array([ -2.08397511,  -1.96070053,  -2.12119911, ...,  -9.56084447,
         -10.50707636,  -8.83345912])],
 [array([ 2.1580194 ,  3.01921404,  2.52794666, ...,  6.208885  ,
          5.5867116 ,  5.1       ])])

In [99]:
#17 (Grad) Write and use a class

# be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values
#     found in the file;
# contain a method, salt_mean, which returns the mean of the salinity;
# contain a method, temp_max, which returns the maximum value of the temperature values.

# loop for general case then with the glob

class dataclass(object):
    
        def __init__(self, filename):
            switch = 0
            self.temp = []
            self.sal = []
            self.f= filename
            f = open(filename)
            
            for line in f.readlines():
                if switch == 1:
                    self.temp.append(line.split()[2])
                    self.sal.append(line.split()[5])
                if line.split()[0] == '*END*': switch = 1
                    
            self.temp = np.asarray(self.temp, dtype = 'float64')
            self.sal = np.asarray(self.sal, dtype = 'float64')
        
        def salt_mean(self):
            saltmean = np.mean(sal)
            return ('This is the mean of the salinity:', saltmean)
    
        def temp_max(self):
            tempmax = np.max(temp)
            return ('This is the maximum temperature value:', tempmax)      
        
        
import glob
filegroup = glob.glob('../python4geosciences/data/MCH/*.cnv2')
# mch('../python4geosciences/data/MCH/m1001a.cnv2')
wind = []
for filename in filegroup:
#     print(filename)
    wind.append(dataclass(filename))
print(wind[1].f)
print(wind[1].sal)
print(wind[1].temp)

../python4geosciences/data/MCH/m1001c.cnv2
[ 24.4009  24.397   24.3957  24.4029  24.4197  24.4626  24.548   24.6361
  24.6538  24.692   24.7626  24.8009  24.8066]
[ 22.0411  22.0391  22.0399  22.0399  22.0498  22.0663  22.0935  22.1243
  22.1312  22.1469  22.1756  22.1909  22.1937]


In [87]:
is_equal?

In [23]:
#18 (Grad) Running mean

def vect_running_mean(vect,N):
    '''Return the running average of a vector, with averaging window of size N.

    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    Outputs:
        out: Vector of running-averaged values; same size as vec'''

    y = np.zeros((len(vect),))
#     if N == 0:
#         return vect
#     else:
    for z in range(len(vect)):
#         fixing for end ranges
#         if z == 
        y[z] = np.sum(vect[z:(z+N+1)]) + np.sum(vect[(z-N):z])
    return y/(2*N+1)

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,1,1,1,1,1,1])
vect_running_mean(b,0)
vect_running_mean(b,1)

array([ 0.66666667,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  0.66666667])